<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header"> 
      	<h1>
        	<?=$this->page_name;?> 
        	<small>Add <?=$this->page_name;?></small> 
      	</h1> 
      	<ol class="breadcrumb">
        	<li><a href="<?php echo $this->url('home');?>dashboard/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        	<li><a href="<?php echo $this->url('home');?>admin/<?=$this->action;?>/"><?=$this->page_name;?></a></li>
        	<li class="active">new</li>
      	</ol>
    </section>

    <!-- Main content --> 
    <section class="content">
      	<div class="row">
        	<!-- right column -->
        	<div class="col-md-6"> 
          		<!-- general form elements -->
          		<div class="box box-primary">
            		<div class="box-header with-border"> 
              		<h3 class="box-title">Information</h3>
            	</div><!-- /.box-header -->
            	<!-- form start -->
            	<form role="form" action="<?php echo $this->url('home');?>admin/<?=$this->action;?>/?task=add" enctype="multipart/form-data" name="quest" method="post">
                	<div class="box-body">
                    	<ul class="nav nav-tabs">
                    	    <?php
                    	    foreach($languages AS $key=>$value){
                    	    ?>
                            <li class="<?=($key==1)?'active':'';?>"> 
                                <a data-toggle="tab" href="#menu<?=$key?>"><?=$value['name'];?></a>
                            </li>
                            <?php
                    	    } 
                            ?>
                        </ul>
                        
                        <div class="tab-content">
                            <?php
                    	    foreach($languages AS $key=>$value){
                    	    ?>
                            <div id="menu<?=$key;?>" class="tab-pane fade in <?=($key==1)?'active':'';?>">
                                <div class="form-group">
                          			<label for="name_<?=$value['code'];?>">Name</label> 
                          			<input type="text" class="form-control " id="name_<?=$value['code'];?>" name="data[name_<?=$value['code'];?>]" placeholder="name" oninput="InvalidMsg(this)" data-ms="name <?=$value['code'];?>" required />
                        		</div>
                            </div>
                            <?php
                    	    } 
                            ?>
                        </div>  
                        
                        <div class="form-group"> 
                  			<label for="category">Category</label>
                  			<select name="data[cate_id]" id="cate_id" class="form-control">
                  			    <?php
                  			    foreach($cate AS $key=>$value){
                  			    ?>
                  			    <option value="<?=$value['id']?>"><?=$value['name']?></option>
                  			    <?php
                  			    }
                  			    ?>
                  			</select> 
                		</div>
                		
                        <div class="form-group"> 
                  			<label for="exampleInputFile">Cover 500x500px</label>
                  			<input type="file" id="pic" name="pic" onchange="imagePreview(this,'img-preview')">
                  			<div id="img-preview"></div>  
                		</div>  
                        <div class="checkbox">
                  			<label>
                    			<input type="checkbox" name="status" value="1" data-toggle="toggle" data-off="Disabled" data-on="Enabled"> Status
                  			</label>
                		</div>
              		</div><!-- /.box-body -->

              		<div class="box-footer">
                		<button type="submit" class="btn btn-primary" style="float:right;">Submit</button>
              		</div>
            	</form>
          	</div>
		</div>
  	</section>
</div>