 
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      	<h1>
        	<?=$detail['name'];?>
        	<small>Preview</small>
      	</h1>
      	<ol class="breadcrumb">
        	<li><a href="<?php echo $this->url('home');?>admin/dashboard/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        	<li><a href="<?php echo $this->url('home');?>admin/admin/">Admin</a></li>
        	<li class="active">edit</li>
      	</ol>
    </section>

    <!-- Main content -->
    <section class="content">
      	<div class="row">
      	   
        	<!-- left column -->
        	<div class="col-md-2">
            	<div class="box box-primary"></div>
                <center><img src="<?=$detail['image'];?>" width="100" alt="<?=$detail['name'];?>"></center>
            </div>
        	<!-- right column -->
        	<div class="col-md-10">
          		<!-- general form elements -->
          		<div class="box box-primary">
            		<div class="box-header with-border"> 
              		<h3 class="box-title">Information</h3>
            	</div><!-- /.box-header --> 
            	<!-- form start -->
            	<form role="form" action="<?php echo $this->url('home');?>admin/admin/?task=edit&id=<?=$detail['id'];?>" onSubmit="return checkEuser()" name="quest" enctype="multipart/form-data" method="post">
                	<input type="hidden" name="id" id="id" value="<?=$detail['id'];?>">
              		<div class="box-body">
                    	<div class="form-group">
                          	<label>Level</label>
                          	<select class="form-control" name="data[level]">
                          	    <option value="1" <?=($detail['level']==1)?'selected':'';?>>Admin</option>
                                <option value="2" <?=($detail['level']==2)?'selected':'';?>>Content</option>
                            </select> 
                        </div>
                		<div class="form-group">
                  			<label for="exampleInputEmail1">Name</label>
                  			<input type="text" class="form-control" id="name" name="data[name]" placeholder="Name" value="<?=$detail['name'];?>">
                		</div>
                        <div class="form-group">
                  			<label for="exampleInputEmail1">Email</label>
                  			<input type="text" class="form-control" id="email" name="data[email]" placeholder="Email" value="<?=$detail['email'];?>">
                		</div>
                        <div class="form-group">
                  			<label for="exampleInputEmail1">Password</label>
                  			<input type="password" class="form-control" id="password" name="data[password]" placeholder="Password" value="">
                		</div>
                		<div class="form-group">
                  			<label for="exampleInputFile">Image 100x100</label>
                  			<input type="file" id="pic" name="pic" onchange="imagePreview(this,'img-preview')">
                  			<div id="img-preview"></div> 
                  			<p class="help-block">Example block-level help text here.</p>
                		</div>
                        
                        <div class="checkbox">
                  			<label>
                    			<input type="checkbox" name="status" value="1" data-toggle="toggle" data-off="Disabled" data-on="Enabled"  <?=($detail['status']==1)?'checked':'';?>> Active
                  			</label>
                		</div>
              		</div>
              		<div class="box-footer">
                		<button type="submit" class="btn btn-primary" style="float:right; padding-right:10px;">Submit</button>
              		</div>
            	</form>
          	</div>
		</div>
  	</section>
</div>