<main id="content" role="main">
    
    <div id="SVGwave1BottomSMShape" class="svg-preloader position-relative gradient-half-primary-v1 overflow-hidden">
      <div class="container space-top-2 space-bottom-3 space-top-md-1 space-top-lg-1">
        <div class="w-md-80 w-lg-60 text-center mx-auto">
          <h1 class="h2 display-6 font-size-md-down-5 text-white"><?=$detail['name_'.$lang];?></span></h1>
          <p class="lead text-white"><?=$this->translate('category list text intro');?></p>
          
        </div>
      </div>

      <!-- SVG Background -->
      <figure class="position-absolute right-0 bottom-0 left-0">
        <img class="js-svg-injector" src="<?=$this->url('home');?>assets/svg/components/wave-1-bottom-sm.svg" alt="Image Description" data-parent="#SVGwave1BottomSMShape">
      </figure>
      <!-- End SVG Background Section -->
    </div> 
    
    <div id="shopItemsContent" class="container space-2 space-md-2">
      <div class="row">
          <?php
          if(!empty($listData['total'])){
              foreach($listData['items'] as $key=>$value){
                include("item-list.phtml");   
              }   
          }else{   
          ?>
            <div class="col-sm-12 col-md-9 col-lg-9 ml-md-auto mr-md-auto text-center">
                <div class="alert alert-danger text-center"> 
                    <h3><?=$this->translate('No Data.');?></h3>   
                </div>
                <a href="<?=$this->url('home').$this->lang;?>/category/"  class="btn btn-primary btn-newpass transition-3d-hover"><i class="fa fa-home" aria-hidden="true"></i> <?=$this->translate('Back');?></a>
            </div>  
          <?php
          }
          ?>
      </div>
      
      <?php
      if(!empty($pagination)){
      ?>
      <!-- Pagination -->
      <div class="d-flex justify-content-between align-items-center">
          <nav aria-label="Page navigation">
              <?php
              print_r($pagination); 
              ?>
          </nav>
      </div>
      <?php
      } 
      ?>
    </div>
</main> 

 