  <!-- ========== MAIN ========== -->
  <main id="content" role="main">
    <!-- Hero Section --> 
    <div id="SVGhireUsBg" class="svg-preloader position-relative gradient-half-primary-v1">
      <div class="container space-2 space-md-2">
        <div class="row justify-content-lg-between align-items-center">
          <div class="col-md-6 col-lg-5">
            <h1 class="display-4 font-size-md-down-5 text-white mb-4"><strong><?=$this->translate('How can Front assistants help you?');?></strong></h1>
            <p class="lead text-white-70"><?=$this->translate("We'd love to talk about how we can help you.");?></p>
          </div>
          <div class="col-md-6">
            <img class="js-svg-injector" src="../../assets/svg/flat-icons/contact-us.svg" alt="SVG Illustration"
                 data-parent="#SVGhireUsBg">
          </div>
        </div>
      </div>

      <!-- SVG Background -->
      <figure class="position-absolute right-0 bottom-0 left-0">
        <img class="js-svg-injector" src="../../assets/svg/components/wave-1-bottom-sm.svg" alt="Image Description"
             data-parent="#SVGhireUsBg">
      </figure>
      <!-- End SVG Background Section -->
    </div>
    <!-- End Hero Section -->

    <!-- Contact Form Section -->
    <div class="container space-2 space-md-3">
      <div class="row justify-content-lg-between">
        <div class="col-lg-6 mb-9 mb-lg-0">
          <!-- Title -->
          <div class="mb-7">
            <h2 class="text-primary font-weight-normal">
              <span class="font-weight-semi-bold"><?=$this->translate('Tell us');?></span>
              <br>
              <?=$this->translate('about yourself');?>
            </h2>
            <p><?=$this->translate('Whether you have questions or you would just like to say hello, contact us.');?></p>
          </div>
          <!-- End Title -->
          
          <form class="js-validate mx-md-auto" name="contact-form" id="contact-form" action="" onsubmit="return false;" method="post" novalidate="novalidate">
            
            <div class="js-form-message form-group">
                <label class="form-label" for="name"><?=$this->translate('Name');?></label> 
                <input type="text" class="form-control success-class" name="name" id="name" value="<?=!empty($this->Users->name)?$this->Users->name:'';?>" placeholder="<?=$this->translate('Name');?>" aria-label="<?=$this->translate('Name');?>" data-msg="<?=$this->translate('Please enter name.');?>" data-error-class="u-has-error" data-success-class="u-has-success" aria-invalid="false">
            </div>
            <!-- Form Group -->
            <div class="js-form-message form-group">
                <label class="form-label" for="email"><?=$this->translate('Email address');?></label>
                <input type="email" class="form-control success-class" name="email" id="email"  value="<?=!empty($this->Users->email)?$this->Users->email:'';?>"  placeholder="<?=$this->translate('Email address');?>" aria-label="<?=$this->translate('Email address');?>" data-msg="<?=$this->translate('Please enter a valid email address.');?>" data-error-class="u-has-error" data-success-class="u-has-success" aria-invalid="false">
            </div>
            <!-- End Form Group -->
            
            <div class="js-form-message form-group">
                <label class="form-label" for="subject"><?=$this->translate('Subject');?></label>
                <input type="text" class="form-control success-class" name="subject" id="subject" placeholder="<?=$this->translate('Subject');?>" aria-label="<?=$this->translate('Subject');?>" data-msg="<?=$this->translate('Please enter subject.');?>" data-error-class="u-has-error" data-success-class="u-has-success" aria-invalid="false">
            </div>
            
            <div class="js-form-message form-group">
                <label class="form-label" for="message"><?=$this->translate('Message');?></label>
                <textarea id="message" name="message" rows="4" placeholder="" class="form-control success-class" placeholder="<?=$this->translate('Message');?>" aria-label="<?=$this->translate('Message');?>" data-msg="<?=$this->translate('Please enter message.');?>" data-error-class="u-has-error" data-success-class="u-has-success" aria-invalid="false"></textarea>
            </div>
               
            <!-- Button -->
            <button type="submit" class="btn btn-primary btn-block btn-contact transition-3d-hover"><?=$this->translate('Send Contact');?></button>
            <!-- End Button -->
          </form>  
          
        </div>

        <div id="SVGwave1BottomShape" class="col-lg-5 svg-preloader d-flex align-items-end bg-img-hero gradient-overlay-half-primary-v1 min-height-550 rounded-top-pseudo" style="background-image: url(../../assets/img/615x750/img4.jpg);">
          <!-- Contacts Info -->
          <div class="position-relative w-100 text-center p-5 pb-9">
            <!-- Info -->
            <div class="mb-5">
              <h2 class="text-white font-weight-semi-bold mb-0"><?=$this->translate('Thailand');?>, <span class="text-warning">TH</span></h2>
              <p class="text-white-70"><?=$this->translate('contact address');?></p>
            </div>
            <!-- End Info -->

            <!-- Info -->
            <div class="mb-5">
              <h3 class="h6 text-white"><?=$this->translate('Phone number');?></h3>
              <span class="d-block h5 text-warning"><?=$this->translate('+66 3444-4479');?></span>
            </div>
            <!-- End Info -->
            
             <!-- Info -->
            <div class="mb-5">
              <h3 class="h6 text-white"><?=$this->translate('Office Hours');?></h3>
              <p class="text-white-70"><?=$this->translate('Monday - Friday: 09:00 AM - 06:00 PM');?> <br><?=$this->translate('Closed on Sunday & Holidays');?></p>
            </div>
            <!-- End Info -->

            
          </div>
          <!-- End Contacts Info -->

          <!-- SVG Bottom Shape -->
          <figure class="position-absolute right-0 bottom-0 left-0">
            <img class="js-svg-injector" src="../../assets/svg/components/wave-4-bottom-sm.svg" alt="Image Description"
                 data-parent="#SVGwave1BottomShape">
          </figure>
          <!-- End SVG Bottom Shape -->
        </div>
      </div>
    </div>
    <!-- End Contact Form Section -->
</main> 
<!-- ========== END MAIN ========== -->
<script type="text/javascript">

$("form[name='contact-form']").validate({ 
  rules: {  
    name: "required",
    email: {
      required: true,
      email: true
    }, 
    subject: "required",
    message: "required"
  },     
  messages: {
    name: $('#name').data('msg'),
    email: $('#email').data('msg'),
    subject: $('#subject').data('msg'),
    message:$('#message').data('msg')
  },    
  submitHandler: function(form) {
    btn_loader = $('.btn-contact');  
    $('.btn-contact').buttonLoader('start'); 
    
    $.ajax({   
        url: base_url+action+'/?act=contact&rd='+makeid(), 
        type: "POST",   
        dataType: "json",  
        data: $(form).serialize(),    
        cache: false,              
        processData: false,      
        success: function(data) { 
            
            setTimeout(function(){    
      				$(btn_loader).buttonLoader('stop');	
      		 	},500);
      		 	
      			if(data.status==200){ 
      			   alert_success(data.items); 
      			   setTimeout(function(){  
                  window.location = base_url+'?rd='+makeid();
      			   },500); 
      			}else{  
      			  alert_error(data.items); 
      				setTimeout(function(){   
          				$(btn_loader).buttonLoader('stop');	
          		},100);   
      			} 
          },  
          error: function(e) {
                console.log(e);
                setTimeout(function(){   
    				$(btn_loader).buttonLoader('stop');	
    		 	},100);    
		      alert_error(error_alert);  
        } 
    });
    return false;  
  }, 
  highlight: function(element, errorClass, validClass) {
    $(element).removeClass('success-class').addClass('error-class');
  },
  unhighlight: function(element, errorClass, validClass) {
    $(element).removeClass('error-class').addClass('success-class');
  }
});

</script>