
<!-- ========== FOOTER ========== -->
<footer class="border-top">
    <!-- Lists -->
    <div class="border-bottom">
        <div class="container space-2">
            <div class="row justify-content-md-between">
                <div class="col-6 col-sm-4 col-md-4 col-lg-4 mb-8 mb-lg-0">
                    <h4 class="h6 font-weight-semi-bold"><?=$this->translate('About');?></h4>

                    <!-- List Group -->
                    <ul class="list-group list-group-flush list-group-borderless mb-0">
                        <li><a class="list-group-item list-group-item-action" href="<?=$this->url('home').$this->lang;?>/about/"><?=$this->translate('About');?></a></li>
                        <li><a class="list-group-item list-group-item-action" href="<?=$this->url('home').$this->lang;?>/projects/"><?=$this->translate('Project');?></a></li>
                        <li><a class="list-group-item list-group-item-action" href="<?=$this->url('home').$this->lang;?>/contact/"><?=$this->translate('Contact Us');?></a></li>
                    </ul>
                    <!-- End List Group -->
                </div>
                

                <div class="col-6 col-sm-4 col-md-4 col-lg-4 mb-8 mb-4 mb-lg-0">
                    <h4 class="h6 font-weight-semi-bold"><?=$this->translate('Resources');?></h4>

                    <!-- List Group -->
                    <ul class="list-group list-group-flush list-group-borderless mb-0">
                        <li><a class="list-group-item list-group-item-action" href="<?=$this->url('home').$this->lang;?>/how-to-work/"><?=$this->translate('Help');?></a></li>
                        <li><a class="list-group-item list-group-item-action" href="<?=$this->url('home').$this->lang;?>/terms/"><?=$this->translate('Terms');?></a></li>
                        <li><a class="list-group-item list-group-item-action" href="<?=$this->url('home').$this->lang;?>/privacy/"><?=$this->translate('Privacy');?></a></li>
                    </ul>
                    <!-- End List Group -->
                </div> 
                
                <div class="col-6 col-sm-4 col-md-4 col-lg-4 col-lg-4">
                    <h4 class="h6 font-weight-semi-bold mb-4"><?=$this->translate('We are driven to deliver results for all your businesses.');?></h4>

                    <!-- Button -->
                    <button type="button" class="btn btn-xs btn-dark btn-wide transition-3d-hover text-left mb-2 mr-1">
                      <span class="media align-items-center">
                        <span class="fab fa-apple fa-2x mr-3"></span>
                        <span class="media-body">
                          <span class="d-block"><?=$this->translate('Download on the');?></span>
                          <strong class="font-size-1"><?=$this->translate('App Store');?></strong>
                        </span>
                      </span>
                    </button>
                    <!-- End Button -->

                    <!-- Button -->
                    <button type="button" class="btn btn-xs btn-dark btn-wide transition-3d-hover text-left mb-2">
                      <span class="media align-items-center">
                        <span class="fab fa-google-play fa-2x mr-3"></span>
                        <span class="media-body">
                          <span class="d-block"><?=$this->translate('Get it on');?></span>
                          <strong class="font-size-1"><?=$this->translate('Google Play');?></strong>
                        </span>
                      </span>
                    </button>
                    <!-- End Button -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Lists -->

    <!-- Copyright -->
    <div class="container text-center space-1">
        <!-- Logo -->
        <a class="d-inline-flex align-items-center mb-2" href="index.html" aria-label="Front">
        
        <span class="brand"><?=$this->translate('Prizzit');?></span>
      </a>
        <!-- End Logo -->
        <p class="small text-muted"><?=$this->translate('© Prizzit. 2019 Htmlstream. All rights reserved.');?></p>
    </div>
    <!-- End Copyright -->
</footer>
<!-- ========== END FOOTER ========== -->

<!-- Go to Top -->
<a class="js-go-to u-go-to" href="#" data-position='{"bottom": 15, "right": 15 }' data-type="fixed" data-offset-top="400" data-compensation="#header" data-show-effect="slideInUp" data-hide-effect="slideOutDown">
<span class="fas fa-arrow-up u-go-to__inner"></span>
</a>
<!-- End Go to Top -->
<?php
echo $this->Users->id;
if(empty($this->Users->id)){  
    if($action != 'login' && $action != 'register' && $action != 'forgotpass'){ 
    ?>  

<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" styles="display:none;">
    <div class="modal-dialog modal-lg">
        <form class="js-validate mx-md-auto" name="loginform" id="loginform" action="" onsubmit="return false;" method="post"   novalidate="novalidate">
            <!-- Title -->
            <div class="mb-7">
                <h2 class="h3 font-weight-normal mb-0"><?=$this->translate('Login'); ?></h2>
                <p><?=$this->translate('Login to manage your account.'); ?></p>
            </div>
            <!-- End Title -->
            <div class="js-form-message form-group"> 
                <button type="button" onclick="connectFackbook();" class="btn btn-facebook btn-block"><i class="fab fa-facebook-f fa-2x"></i><?=$this->translate('Signin With Facebook'); ?></button>
            </div>
            <div class="js-form-message form-group"> 
                <a href="<?=$this->url('home').$this->lang;?>/loginLine/?act=login&return_url=<?=$FullLink;?>" class="btn btn-line btn-block"><i class="fab fa-line fa-2x"></i><?=$this->translate('Signin With Line'); ?></a>
            </div> 
            <p class="text-center mb-3 mt-3 text-or"><?=$this->translate('or with your email'); ?></p> 

            <!-- Form Group -->
            <div class="js-form-message form-group">
                <label class="form-label" for="signinSrEmail"><?=$this->translate('Email address'); ?></label>
                <input type="email" class="form-control" name="email" id="signinSrEmail" placeholder="<?=$this->translate('Email address'); ?>" aria-label="<?=$this->translate('Email address'); ?>" data-msg="<?=$this->translate('Please enter a valid email address.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
            </div>
            <!-- End Form Group -->
            

            <!-- Form Group -->
            <div class="js-form-message form-group">
                <label class="form-label" for="signinSrPassword">
                    <span class="d-flex justify-content-between align-items-center">
                      <?=$this->translate('Password'); ?>
                      <a class="link-muted text-capitalize font-weight-normal" href="<?=$this->url('home').$this->lang;?>/forgotpass/"><?=$this->translate('Forgot Password?'); ?></a>
                    </span>
                </label>
                <input type="password" class="form-control" name="password" id="signinSrPassword" placeholder="********" aria-label="********" data-msg="<?=$this->translate('Your password is invalid. Please try again.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
            </div>
            <!-- End Form Group -->
 
            <!-- Button -->
            <div class="row align-items-center mb-5">
                <div class="col-6">
                    <span class="small text-muted"><?=$this->translate("Don't have an account?"); ?></span>
                    <a class="small" href="javascript:popupModal('register');"><?=$this->translate('Signup'); ?></a>
                </div>

                <div class="col-6 text-right">
                    <button type="submit" class="btn btn-primary btn-login transition-3d-hover"><?=$this->translate('Get Started'); ?></button>
                </div>
            </div>
            <!-- End Button -->
        </form>
    </div>
</div>

<div class="modal fade" id="register-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" styles="display:none;">
    <div class="modal-dialog modal-lg">
        <form class="js-validate mx-md-auto" name="registerform" id="registerform" action="" onsubmit="return false;" method="post"  novalidate="novalidate">
            <!-- Title -->
            <div class="mb-7">
                <h1 class="h3 text-primary font-weight-normal mb-0"><?=$this->translate('Signup'); ?></h1>
                <p><?=$this->translate('or with your email'); ?></p>
            </div> 
            <!-- End Title -->
            <div class="js-form-message form-group"> 
                <button type="button" onclick="connectFackbook();" class="btn btn-facebook btn-block"><i class="fab fa-facebook-f fa-2x"></i><?=$this->translate('Signup With Facebook'); ?></button>
            </div>
            <div class="js-form-message form-group"> 
                <a href="<?=$this->url('home').$this->lang;?>/loginLine/?act=login&return_url=<?=$FullLink;?>" class="btn btn-line btn-block"><i class="fab fa-line fa-2x"></i><?=$this->translate('Signup With Line'); ?></a>
            </div> 
            <p class="text-center mb-3 mt-3 text-or"><?=$this->translate('or with your email'); ?></p>
            
            <!-- Form Group -->
            <div class="js-form-message form-group"> 
                <input type="text" class="form-control" name="name" id="signinSrName" placeholder="<?=$this->translate('Name'); ?>" aria-label="<?=$this->translate('Name'); ?>" data-msg="<?=$this->translate('Please enter full name.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
            </div>
            <!-- End Form Group --> 
            
            <!-- Form Group -->
            <div class="js-form-message form-group">
                <input type="email" class="form-control" name="email" id="signupSrEmail" placeholder="<?=$this->translate('Email address'); ?>" aria-label="<?=$this->translate('Email address'); ?>" data-msg="<?=$this->translate('Please enter a valid email address.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
            </div>
            <!-- End Form Group -->

            <!-- Form Group -->
            <div class="js-form-message form-group">
                <input type="password" class="form-control" name="password" id="signupSrPassword" placeholder="Password" aria-label="********" data-msg="<?=$this->translate('Your password is invalid. Please try again.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
            </div>
            <!-- End Form Group -->

            <!-- Form Group -->
            <div class="js-form-message form-group">
                <input type="password" class="form-control" name="confirmPassword" id="signinSrConfirmPassword" placeholder="<?=$this->translate('Confirm password'); ?>" aria-label="********" data-msg="<?=$this->translate('Password does not match the confirm password.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
            </div> 
            <!-- End Form Group -->
            <?php
            if(0){
            ?>
            <!-- Checkbox -->
            <div class="js-form-message mb-5">
                <div class="custom-control custom-checkbox d-flex align-items-center text-muted">
                    <input type="checkbox" class="custom-control-input" id="termsCheckbox" name="termsCheckbox"  data-msg="<?=$this->translate('Please accept our Terms and Conditions.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
                    <label class="custom-control-label" for="termsCheckbox">
                      <small>
                        <?=$this->translate('I agree to the'); ?>
                        <a class="link-muted" href="#"><?=$this->translate('Terms and Conditions'); ?></a>
                      </small>
                    </label>
                </div>
            </div>
            <!-- End Checkbox -->
            <?php
            }  
            ?>
            <!-- Button  --->   
            <div class="row align-items-center mb-5">
                <div class="col-5 col-sm-6"> 
                    <span class="small text-muted"><?=$this->translate('Already have an account?'); ?></span>
                    <a class="small" href="javascript:popupModal('login');"><?=$this->translate('Login'); ?></a>
                </div>
 
                <div class="col-7 col-sm-6 text-right">
                    <button type="submit" class="btn btn-primary btn-register transition-3d-hover"><?=$this->translate('Get Started'); ?></button>
                </div>
            </div>
            <!-- End Button -->
        </form>
    </div>
</div> 

<?php
    } 
}
?> 
