

<!-- ========== MAIN CONTENT ========== -->
<main class="content" id="content" role="main">
    <!-- Hero Section -->
    <div class="container mobile-site space-2 space-md-2">
        <div class="row align-items-lg-center mobile-site mt-5">
            <div class="col-sm-12 col-md-10 col-lg-7 ml-md-auto mr-md-auto mobile-site mt-5">
                <!-- Info -->
                <div class="mb-4 text-center">
                    <h1 class="mobile-site h1"><?=$this->translate('Create a money pot for'); ?></h1>
                    <p class="home-intro"><?=$this->translate('Group Gift - Project & Causes - Common Expenses'); ?></p>
                </div>
                <!-- End Info -->

                <!-- Form -->
                <form class="js-validate mb-3" name="home-createpot" id="home-createpot" action="<?=$this->url('home').$this->lang;?>/create/" onsubmit="return false;" method="get">
                    <div class="form-row">
                        <div class="col-12 col-sm-8 mb-2">
                            <div class="js-form-message"> 
                                <label class="sr-only" for="createpot"><?=$this->translate('Create a money for your money pot'); ?></label>
                                <div class="input-group home-createpot">
                                    <input type="text" class="form-control" name="potname" id="potname" placeholder="<?=$this->translate('Create a money for your money pot'); ?>" aria-label="<?=$this->translate('Create a money for your money pot'); ?>"  data-msg="<?=$this->translate('Please enter  a money for your money pot'); ?>" data-error-class="u-has-error"
                                        data-success-class="u-has-success">
                                </div> 
                            </div>
                        </div> 
                        <div class="col-12 col-sm-4"> 
                            <button type="submit" class="btn btn-primary btn-block btn-wide transition-3d-hover"><?=$this->translate('CREATE'); ?></button>
                        </div>
                    </div>
                </form> 
                <!-- End Form -->
            </div>
        </div>
    </div>
    <!-- End Hero Section -->
   
    <?php
    if(!empty($cateList)){ 
    ?>
    <!-- Clients Section -->
    <div class="container px-2"> 
        <div class="w-md-80 w-lg-80 text-center mx-md-auto mobile-site mt-9 mb-9"> 
            <h2 class="h3 font-weight-marmal text-intro"><?=$this->translate('Create a money pot for anyting you can think of'); ?></h2>
        </div>
        
        <div class="js-slick-carousel u-slick u-slick--gutters-1" data-autoplay="true" data-speed="5000" data-infinite="true" data-slides-show="6" data-responsive='[{
             "breakpoint": 1200,
             "settings": {
               "slidesToShow": 4
             }
           }, {
             "breakpoint": 992,
             "settings": {
               "slidesToShow": 4
             }
           }, {
             "breakpoint": 768,
             "settings": {
               "slidesToShow": 3
             }
           }, {
             "breakpoint": 576,
             "settings": {
               "slidesToShow": 3
             }
           }, {
             "breakpoint": 480,
             "settings": {
               "slidesToShow": 2
             }
           }]'>
            <?php 
            //print_r($cateList); 
            foreach($cateList as $key=>$value){  
            ?>
            <div class="js-slide">
                <div class="bg-light rounded">
                    <a href="<?=$this->url('home').$this->lang;?>/category-list/<?=$value['slugify'];?>">
                        <img class="u-clients" src="<?=$value['image']?>" alt="<?=$value['name']?>">
                        <p style="text-align:center;"> <?= $value['name'] ?></p>
                    </a>
                </div>
            </div>
            <?php
            }
            if(0){  
            ?>
            <div class="js-slide">
                <div class="bg-light rounded">
                    <a href="">
                        <img class="u-clients" src="https://images.unsplash.com/photo-1524538392646-30e167f63062?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="Image Description">
                    </a>
               </div>
            </div>
            <div class="js-slide">
                <div class="bg-light rounded">
                    <img class="u-clients" src="https://images.unsplash.com/photo-1524538392646-30e167f63062?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="Image Description">
                </div>
            </div>
            <div class="js-slide">
                <div class="bg-light rounded">
                    <img class="u-clients" src="https://images.unsplash.com/photo-1524538392646-30e167f63062?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="Image Description">
                </div>
            </div>
            <div class="js-slide">
                <div class="bg-light rounded">
                    <img class="u-clients" src="https://images.unsplash.com/photo-1524538392646-30e167f63062?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="Image Description">
                </div>
            </div>
            <div class="js-slide">
                <div class="bg-light rounded">
                    <img class="u-clients" src="https://images.unsplash.com/photo-1524538392646-30e167f63062?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="Image Description">
                </div>
            </div>
            <div class="js-slide">
                <div class="bg-light rounded">
                    <img class="u-clients" src="https://images.unsplash.com/photo-1524538392646-30e167f63062?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="Image Description">
                </div>
            </div>
            <div class="js-slide">
                <div class="bg-light rounded">
                    <img class="u-clients" src="https://images.unsplash.com/photo-1524538392646-30e167f63062?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="Image Description">
                </div>
            </div>
            <?php
            }
            ?>
        </div>
    </div>
    <!-- End Clients Section -->
    <?php
    }
    ?>
</main>
<!-- ========== END MAIN CONTENT ========== -->
  