<main id="content" role="main">
    <!-- Search Section -->
    <div class="gradient-half-primary-v1">
      <div class="bg-img-hero-center" style="background-image: url(../../assets/svg/components/bg-elements-10.svg);">
        <div class="container space-2 space-md-2">
          <div class="w-lg-80 mx-lg-auto">
            <!-- Input -->
            <form class="input-group input-group-borderless">
              <div class="input-group-prepend">
                <span class="input-group-text" id="askQuestions">
                  <span class="fas fa-search"></span>
                </span>
              </div>
              <input type="search" class="form-control" placeholder="Search for answers" aria-label="Search for answers" aria-describedby="askQuestions">
            </form>
            <!-- End Input -->
          </div>
        </div>
      </div>
    </div>
    <!-- End Search Section -->

    <!-- Article Section -->
    <div class="container space-bottom-2">
      <div class="w-lg-80 mx-lg-auto">
        <!-- Breadcrumbs -->
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-no-gutter font-size-1 space-1">
            <li class="breadcrumb-item"><a href="help.html">Front Help Center</a></li>
            <li class="breadcrumb-item"><a href="help.html">Getting started</a></li>
            <li class="breadcrumb-item active" aria-current="page">What's Front?</li>
          </ol>
        </nav>
        <!-- End Breadcrumbs -->

        <!-- Article -->
        <div class="card shadow-sm p-7">
          <h1 class="h2 font-weight-medium">What's Front?</h1>
          <p>How Front works, what it can do for your business and what makes it different to other solutions.</p>

          <!-- Article Authors -->
          <div class="media mb-5">
            <div class="u-sm-avatar u-avatar--bordered rounded-circle mr-2">
              <img class="img-fluid rounded-circle" src="../../assets/img/100x100/img1.jpg" alt="Image Description">
            </div>

            <div class="media-body">
              <small class="d-block">
                <span class="text-muted">Written by</span>
                Luisa Woodfine
              </small>
              <small class="d-block text-secondary">
                Updated over a week ago
              </small>
            </div>
          </div>
          <!-- End Article Authors -->

          <p>Front is an incredibly beautiful, fully responsive, and mobile-first projects on the web – it is the perfect starting point for any creative and professional sites. Get started with Front's components and options for laying out your Front project, including SVG components, powerful scripts, fully detailed documentation, and yet developer friendly code.</p>

          <!-- Alert -->
          <div class="alert alert-warning p-4 mb-5" role="alert">
            <div class="media">
              <span class="fas fa-magic font-size-2 mt-1 mr-3"></span>
              <div class="media-body">
                <strong>Bonus.</strong> Sketch is small bonus that has some of the theme. Front's Sketch file comes with all demo pages design only. Front is not only for developers but also for designers.
              </div>
            </div>
          </div>
          <!-- End Alert -->

          <h2 class="h5">Free updates and support</h2>
          <p>We would like to draw your attention to the fact that after purchasing a Front Template copy, you get the right for a <strong>lifetime</strong> entitlement to download updates for <strong>FREE!</strong> Need help? For any questions or concerns, reach us out at <a href="mailto:support@htmlstream.com">support@htmlstream.com</a>.</p>

          <ul class="text-secondary">
            <li class="pb-2"><strong>Free updates:</strong> Front offers a lifetime free updates. This means you will never pay for any bug-fixes and compatibility upgrades for your theme, ever.</li>
            <li class="pb-2"><strong>Technical support:</strong> As always, our Customer Support team is available 24/7 to answer any questions you might have. We will do our best to get back to you within <strong>24-48 hours</strong>.</li>
          </ul>

          <p>Front Template is built by the team that has customers in the background such us Stanford University, The University of Maryland, University of Victoria and many more Governments, Corporate Agencies. To bring the most modern look of any HTML5 template across all Marketplaces – powered by Bootstrap 4, Front sets the new standard with breathtaking design, top-notch support, and incredible featured packed updates that will save your precious time and gives trendy look to all your web projects. On top of that the creators of Bootstrap have closely monitored the ongoing process of the Front and helped to achieve an enormous result.</p>

          <!-- Resolved -->
          <div class="text-center border-top border-bottom my-6 py-6">
            <h4 class="h6 mb-4">
              <span class="far fa-paper-plane mr-1"></span>
              Was this article helpful?
            </h4>

            <button type="button" class="btn btn-sm btn-primary btn-wide mb-2 mx-1">Yes, thanks!</button>
            <button type="button" class="btn btn-sm btn-soft-primary btn-wide mb-2 mx-1">Not really</button>
          </div>
          <!-- End Resolved -->

          <!-- Related Articles -->
          <div class="mb-4">
            <h3 class="h5 font-weight-medium">Related articles</h3>
          </div>

          <ul class="list-unstyled">
            <li class="pb-3"><a class="link-muted" href="help.html">Troubleshoot connection issues</a></li>
            <li class="pb-3"><a class="link-muted" href="help.html">Getting started for workspace creators</a></li>
            <li class="pb-3"><a class="link-muted" href="help.html">Edit your profile</a></li>
          </ul>
          <!-- End Related Articles -->
        </div>
        <!-- End Article -->
      </div>
    </div>
    <!-- End Article Section -->
</main>
