<!-- ========== MAIN CONTENT ========== -->
<main class="content" id="content" role="main">
    <div class="container space-2 space-md-2">
        <div class="row">
            <div class="col-sm-10 col-md-10 col-lg-10 ml-md-auto mr-md-auto">
                 
                <?php
                include("topedit.phtml"); 
                ?> 
                
                <div class="row">
                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <?php 
                        include("menu.phtml");
                        ?>
                    </div>
                    <div class="col-sm-9 col-md-9 col-lg-9">
                        <!-- Card -->
                        <form id="emailinvite" name="emailinvite" action="" method="post" >
                            <input type="hidden" name="task" id="task" name="task" value="invite"/>
                            <div class="card mb-3">  
                                <div class="card-body">
                                    <h3 class="h3 mb-5 mt-2"><?=$this->translate('Manage invitations'); ?></h3> 
                                    <div class="table-responsive">
                    		        	<table class="table table-light">
                    					  <thead> 
                    					    <tr> 
                    					      <th>
                					            <div class="custom-control custom-checkbox d-flex align-items-center">
                                                    <input type="checkbox" class="custom-control-input" id="select_all">
                                                    <label class="custom-control-label" for="select_all">
                                                      <span class="text-hide"><?=$this->translate('Checkbox'); ?></span>
                                                    </label>
                                                </div>
                                              </th> 
                    					      <th><?=$this->translate('Email'); ?></th>
                    					      <th><?=$this->translate('Invited on'); ?></th>
                    					      <th><?=$this->translate('Remind'); ?></th>
                    					      <th><?=$this->translate('Participant'); ?></th> 
                    					    </tr>    
                    					  </thead>
                    					  <tbody>
                    					  	<?php
                    					  	//$page = 1;
                    					  	$count = 1;
                    					  	if($page>1){ 
                    					  		$count = ((($pageshow*$page)+$count)-$pageshow);	
                    					  	} 
                    					  	if(!empty($emailList['total'])){ 
                    					  		foreach($emailList['data'] as $key=>$val){
                    					  	?> 
                    						    <tr>
                    						      <td>
                    						          <div class="custom-control custom-checkbox d-flex align-items-center">
                                                        <input type="checkbox" class="custom-control-input checkbox"  name="invite[]" value="<?=$val['id'];?>" id="checkbox<?=$count;?>">
                                                        <label class="custom-control-label" for="checkbox<?=$count;?>">
                                                          <span class="text-hide"><?=$this->translate('Checkbox'); ?></span>
                                                        </label>
                                                      </div>
                    						      </td> 
                    						      <td><?=$val['email'];?></td> 
                    						      <?php
                    						      	if(trim($val['invited'])>0){
                    						      		$status = '<span class="badge badge-pill badge-success">'.$this->translate('Yes').'</span>';
                    						      	}else{
                    						      		$status = '<span class="badge badge-pill badge-secondary">'.$this->translate('No').'</span>';
                    						      	} 
                    						      	 
                    						      	if(trim($val['remind'])==1){
                    						      		$remind = '<span class="badge badge-pill badge-primary">'.$this->translate('3 Day').'</span>';
                    						      	}else if(trim($val['remind'])==2){
                    						      		$remind = '<span class="badge badge-pill badge-warning">'.$this->translate('1 week').'</span>';
                    						      	}else{  
                    						      		$remind = '<span class="badge badge-pill badge-secondary">'.$this->translate('none').'</span>';
                    						      	}   
                    						      	
                    						      ?>    
                    						      <td><?=date("d F Y H:i", strtotime($val['invite_date']));?></td>
                    						      <td><?=$remind;?></td>  
                    						      <td><?=$status;?></td>  
                    						       
                    						    </tr>   
                    					    <?php
                    					    		$count++; 
                    					  		}
                    					    }else{
                    					    ?>
                    					    	<tr>
                    					    		<td colspan="5" align="center"><?=$this->translate('No Data'); ?></td>
                    					    	</tr>
                    					    <?php
                    					    }
                    					    ?>
                    					  </tbody>
                    					</table>
                    				</div> 
                    				<hr />
                    				<div class="row">
                    				    <div class="col text-left pb-5">
                    				        <button type="button" class="btn btn-primary btn-sm btn-invite disabled" onclick="sendInvite();"><i class="fa fa-paper-plane" aria-hidden="true"></i> <?=$this->translate('Send invite again'); ?></button>
                    				        <button type="button" class="btn btn-danger btn-sm btn-delete disabled" onclick="remove();"><i class="fa fa-trash" aria-hidden="true"></i> <?=$this->translate('Delete'); ?></button>
                    				    </div>     
                    					<div class="col text-right pb-5">
                    						<?php 
                    						print_r($pagination);
                    						?>
                    					</d>
                    				</div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>
</main>
<!-- ========== END MAIN CONTENT ========== -->
<script type="text/javascript">
var id = '<?=$id;?>';
function remove(){
    $("#task").val('del'); 
    if(document.querySelectorAll('.checkbox:checked').length){
         swal({ 
           title: "Are you sure remove.",
           type: "warning", 
           showCancelButton: true, 
           confirmButtonText: "Yes",
           cancelButtonText: "No", 
        }).then(function() { 
            $("#emailinvite").submit();
        },function(dismiss) {
          if(dismiss == 'cancel') {
              
          }
        });
    }
}

function sendInvite(){
    $("#task").val('invite');  
    if(document.querySelectorAll('.checkbox:checked').length){
         swal({ 
           title: "Are you sure send to invite.",
           type: "warning", 
           showCancelButton: true, 
           confirmButtonText: "Yes",
           cancelButtonText: "No", 
        }).then(function() { 
            $("#emailinvite").submit();
        },function(dismiss) {
          if(dismiss == 'cancel') {
              
          }
        });
    } 
}

var select_all = document.getElementById("select_all");
var checkboxes = document.getElementsByClassName("checkbox");

select_all.addEventListener("change", function(e){
	for (i = 0; i < checkboxes.length; i++) { 
		checkboxes[i].checked = select_all.checked;
	}
	if(document.querySelectorAll('.checkbox:checked').length){
	    $(".btn-invite, .btn-delete").removeClass("disabled");
	}else{
	    $(".btn-invite, .btn-delete").addClass("disabled");
	}
});


for (var i = 0; i < checkboxes.length; i++) {
	checkboxes[i].addEventListener('change', function(e){ 
		if(this.checked == false){
			select_all.checked = false;
		}
		if(document.querySelectorAll('.checkbox:checked').length == checkboxes.length){
			select_all.checked = true;
		}
		if(document.querySelectorAll('.checkbox:checked').length){
    	    $(".btn-invite, .btn-delete").removeClass("disabled");
    	}else{
    	    $(".btn-invite, .btn-delete").addClass("disabled");
    	} 
	});
} 
</script>