<main id="content" role="main" class="" style="">
    <!-- Privacy Section -->
    <div class="container space-top-2 space-bottom-1 overflow-hidden">
        <div class="w-lg-80 mx-lg-auto">
            <div class="card shadow-sm">
                <!-- Hero -->
                <div class="card-header position-relative gradient-half-primary-v1 space-top-2 space-bottom-3 rounded-top-pseudo px-7 px-md-9">
                    <h1 class="text-white font-weight-semi-bold">Privacy &amp; Policy</h1>
                    <p class="text-white-70">Last modified: March 27, 2018 (<a class="text-light" href="#">view archived versions</a>)</p>

                    <!-- SVG Bottom Shape -->
                    <figure class="position-absolute right-0 bottom-0 left-0">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" x="0px" y="0px" width="100%" height="140px" viewBox="0 0 300 100" style="margin-bottom: -8px; enable-background:new 0 0 300 100;" xml:space="preserve"
                            class="injected-svg js-svg-injector" data-parent="#content">
                            <style type="text/css">
                              .wave-bottom-1-sm-0{fill:#FFFFFF;}
                            </style>
                            <g>
                              <defs>
                                <rect id="waveBottom1SMID1" width="300" height="100"></rect>
                              </defs>
                              <clipPath id="waveBottom1SMID2">
                                <use xlink:href="#waveBottom1SMID1" style="overflow:visible;"></use>
                              </clipPath>
                              <path class="wave-bottom-1-sm-0 fill-white" opacity=".4" clip-path="url(#waveBottom1SMID2)" d="M10.9,63.9c0,0,42.9-34.5,87.5-14.2c77.3,35.1,113.3-2,146.6-4.7C293.7,41,315,61.2,315,61.2v54.4H10.9V63.9z"></path>
                              <path class="wave-bottom-1-sm-0 fill-white" opacity=".4" clip-path="url(#waveBottom1SMID2)" d="M-55.7,64.6c0,0,42.9-34.5,87.5-14.2c77.3,35.1,113.3-2,146.6-4.7c48.7-4.1,69.9,16.2,69.9,16.2v54.4H-55.7     V64.6z"></path>
                              <path class="wave-bottom-1-sm-0 fill-white" opacity=".4" fill-opacity="0" clip-path="url(#waveBottom1SMID2)" d="M23.4,118.3c0,0,48.3-68.9,109.1-68.9c65.9,0,98,67.9,98,67.9v3.7H22.4L23.4,118.3z"></path>
                              <path class="wave-bottom-1-sm-0 fill-white" clip-path="url(#waveBottom1SMID2)" d="M-54.7,83c0,0,56-45.7,120.3-27.8c81.8,22.7,111.4,6.2,146.6-4.7c53.1-16.4,104,36.9,104,36.9l1.3,36.7l-372-3     L-54.7,83z"></path>
                            </g>
                        </svg>
                    </figure>
                    <!-- End SVG Bottom Shape Section -->
                </div>
                <!-- End Hero -->

                <!-- Content -->
                <div class="card-body p-7 p-md-9">
                    <div class="mb-7">
                        <!-- Title -->
                        <div class="mb-3">
                            <h3 class="h5 text-primary font-weight-semi-bold">Introduction</h3>
                        </div>
                        <!-- End Title -->

                        <!-- Text -->
                        <p>Thanks for using our products and services ("Services"). The Services are provided by Pixeel Ltd. ("Front"), located at 153 Williamson Plaza, Maggieberg, MT 09514, England, United Kingdom.
                        </p>
                        <p>By using our Services, you are agreeing to these terms. Please read them carefully.</p>
                        <p>Our Services are very diverse, so sometimes additional terms or product requirements (including age requirements) may apply. Additional terms will be available with the relevant Services, and those additional terms become part
                            of your agreement with us if you use those Services.</p>
                        <!-- End Text -->
                    </div>

                    <div class="mb-7">
                        <!-- Title -->
                        <div class="mb-3">
                            <h3 class="h5 text-primary font-weight-semi-bold">Using our services</h3>
                        </div>
                        <!-- End Title -->

                        <!-- Text -->
                        <p>You must follow any policies made available to you within the Services.</p>
                        <p>Don't misuse our Services. For example, don't interfere with our Services or try to access them using a method other than the interface and the instructions that we provide. You may use our Services only as permitted by law, including
                            applicable export and re-export control laws and regulations. We may suspend or stop providing our Services to you if you do not comply with our terms or policies or if we are investigating suspected misconduct.</p>
                        <p>Using our Services does not give you ownership of any intellectual property rights in our Services or the content you access. You may not use content from our Services unless you obtain permission from its owner or are otherwise
                            permitted by law. These terms do not grant you the right to use any branding or logos used in our Services. Don't remove, obscure, or alter any legal notices displayed in or along with our Services.</p>
                        <!-- End Text -->
                    </div>

                    <div class="mb-7">
                        <!-- Title -->
                        <div class="mb-3">
                            <h3 class="h5 text-primary font-weight-semi-bold">Privacy and copyright protection</h3>
                        </div>
                        <!-- End Title -->

                        <!-- Text -->
                        <p>Front's privacy policies explain how we treat your personal data and protect your privacy when you use our Services. By using our Services, you agree that Front can use such data in accordance with our privacy policies.</p>
                        <p>We respond to notices of alleged copyright infringement and terminate accounts of repeat infringers according to the process set out in the U.S. Digital Millennium Copyright Act.</p>
                        <p>We provide information to help copyright holders manage their intellectual property online. If you think somebody is violating your copyrights and want to notify us, you can find information about submitting notices and Front's
                            policy about responding to notices in <a href="help.html">our Help Center</a>.</p>
                        <!-- End Text -->
                    </div>

                    <div class="mb-7">
                        <!-- Title -->
                        <div class="mb-3">
                            <h3 class="h5 text-primary font-weight-semi-bold">Your content in our services</h3>
                        </div>
                        <!-- End Title -->

                        <!-- Text -->
                        <p>Some of our Services allow you to upload, submit, store, send or receive content. You retain ownership of any intellectual property rights that you hold in that content. In short, what belongs to you stays yours.</p>
                        <p>When you upload, submit, store, send or receive content to or through our Services, you give Front (and those we work with) a worldwide license to use, host, store, reproduce, modify, create derivative works (such as those resulting
                            from translations, adaptations or other changes we make so that your content works better with our Services), communicate, publish, publicly perform, publicly display and distribute such content. The rights you grant in this
                            license are for the limited purpose of operating, promoting, and improving our Services, and to develop new ones. This license continues even if you stop using our Services (for example, for a business listing you have added
                            to Front Maps). Some Services may offer you ways to access and remove content that has been provided to that Service. Also, in some of our Services, there are terms or settings that narrow the scope of our use of the content
                            submitted in those Services. Make sure you have the necessary rights to grant us this license for any content that you submit to our Services.</p>
                        <!-- End Text -->
                    </div>
                </div>
                <!-- End Content -->
            </div>
        </div>
    </div>
    <!-- End Privacy Section -->

    <!-- SVG Background Shapes - Left Side -->
    <div class="w-25 content-centered-y left-0 z-index-n1 mt-9">
        <figure class="ie-circle-1">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" x="0px" y="0px" viewBox="0 0 260 260" style="enable-background:new 0 0 260 260;" xml:space="preserve" class="injected-svg js-svg-injector" data-parent="#content">
                <style type="text/css">
                	.circle-1-0{fill:#F8FAFD;}
                </style>
                <circle class="circle-1-0 fill-gray-200" cx="130" cy="130" r="130"></circle>
            </svg>
        </figure>
    </div>
    <!-- End SVG Background Shapes - Left Side -->

    <!-- SVG Background Shapes - Right Side -->
    <div class="w-35 content-centered-y right-0 z-index-n1 mt-n9">
        <figure class="ie-bg-elements-4">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none" x="0px" y="0px" viewBox="0 0 130.5 208.9" style="enable-background:new 0 0 130.5 208.9;" xml:space="preserve" class="injected-svg js-svg-injector"
                data-parent="#content">
            <style type="text/css">
            	.bg-elements-4-0{fill:#F8FAFD;}
            </style>
              <path class="bg-elements-4-0 fill-gray-200" d="M130.5,27.4L107.7,7.7C94.4-3.7,74.4-2.3,63,11L7.7,75.1c-11.4,13.2-10,33.2,3.3,44.7l94.4,81.4c7.2,6.2,16.4,8.6,25.2,7.4V27.4z"></path>
            </svg>
                    </figure>
                </div>
                <!-- End SVG Background Shapes - Right Side -->
            
                <!-- SVG Background Shapes -->
                <div class="position-absolute right-0 bottom-0 left-0 z-index-n1">
                    <figure class="ie-bg-elements-3">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1506.3 578.7" style="enable-background:new 0 0 1506.3 578.7;" xml:space="preserve" class="injected-svg js-svg-injector" data-parent="#content">
            <style type="text/css">
            	.bg-elements-3-0{fill:#FFC107;}
            	.bg-elements-3-1{fill:#00DFFC;}
            	.bg-elements-3-2{fill:#00C9A7;}
            	.bg-elements-3-3{fill:#DE4437;}
            	.bg-elements-3-4{fill:#377DFF;}
            </style>
            <g>
            	<path class="bg-elements-3-0 fill-warning" d="M45,91.6L45,91.6c-1.2-1.2-1.2-3.1,0-4.3l9.1-9.1c1.2-1.2,3.1-1.2,4.3,0h0c1.2,1.2,1.2,3.1,0,4.3l-9.1,9.1   C48.2,92.8,46.2,92.8,45,91.6z"></path>
            </g>
            <g>
            	<path class="bg-elements-3-0 fill-warning" d="M58.4,91.6L58.4,91.6c-1.2,1.2-3.1,1.2-4.3,0L45,82.5c-1.2-1.2-1.2-3.1,0-4.3h0c1.2-1.2,3.1-1.2,4.3,0l9.1,9.1   C59.6,88.5,59.6,90.4,58.4,91.6z"></path>
            </g>
            <path class="bg-elements-3-1 fill-info" d="M1041.3,403.1l5.1,19.1c0.7,2.6,4,3.5,5.9,1.6l14-14c1.9-1.9,1-5.2-1.6-5.9l-19.1-5.1  C1043,398,1040.5,400.4,1041.3,403.1z"></path>
            <path class="bg-elements-3-2 fill-success" d="M380.6,577.8l-12.2-12.2c-1.2-1.2-1.2-3.1,0-4.3l12.2-12.2c1.2-1.2,3.1-1.2,4.3,0l12.2,12.2  c1.2,1.2,1.2,3.1,0,4.3l-12.2,12.2C383.8,579,381.8,579,380.6,577.8z"></path>
            <circle class="bg-elements-3-2 fill-success" cx="1494.3" cy="353.5" r="12"></circle>
            <path class="bg-elements-3-3 fill-danger" d="M992,21.5h-15.9c-1.5,0-2.8-1.3-2.8-2.8V2.8c0-1.5,1.3-2.8,2.8-2.8H992c1.5,0,2.8,1.3,2.8,2.8v15.9  C994.8,20.2,993.5,21.5,992,21.5z"></path>
            <path class="bg-elements-3-4 fill-primary" d="M19.3,310.2l-17,4.6c-2.3,0.6-3.1,3.6-1.4,5.3l12.4,12.4c1.7,1.7,4.7,0.9,5.3-1.4l4.6-17  C23.8,311.7,21.7,309.6,19.3,310.2z"></path>
            </svg>
        </figure>
    </div>
    <!-- End SVG Background Shapes -->
</main>
