<main id="content" role="main">

  
    <div id="SVGwave1BottomSMShape" class="svg-preloader position-relative gradient-half-primary-v1 overflow-hidden">
      <div class="container space-top-2 space-bottom-3 space-top-md-1 space-top-lg-1">
        <div class="w-md-80 w-lg-60 text-center mx-auto">
          <h1 class="h2 display-6 font-size-md-down-5 text-white"><?=$this->translate('Donate to social causes & projects');?></span></h1>
          <p class="lead text-white"><?=$this->translate('Discover social causes you can support');?></p>
        </div>
      </div>

      <!-- SVG Background -->
      <figure class="position-absolute right-0 bottom-0 left-0">
        <img class="js-svg-injector" src="<?=$this->url('home');?>assets/svg/components/wave-1-bottom-sm.svg" alt="Image Description"
             data-parent="#SVGwave1BottomSMShape">
      </figure>
      <!-- End SVG Background Section -->
    </div>
    
    
    
    <div id="shopItemsContent" class="container space-2 space-md-2">
      <div class="row">
          <?php
          if(!empty($listData['total'])){
              foreach($listData['items'] as $key=>$value){
                include("item-list.phtml"); 
              }   
          }
          ?> 
      </div>
      
      <?php
      if(!empty($pagination)){
      ?>
      <!-- Pagination -->
      <div class="d-flex justify-content-between align-items-center">
          <nav aria-label="Page navigation">
              <?php
              print_r($pagination); 
              ?>
          </nav>
      </div>
      <?php
      } 
      ?>
    </div>
</main> 

 