<main id="content" role="main">
    <!-- Terms Title Section -->
    <div class="position-relative">
        <div class="container space-2 space-md-2 space-bottom-md-3">
            <div class="w-md-80 w-lg-60">
                <h1 class="text-primary"><span class="font-weight-semi-bold">Front</span> Terms &amp; conditions</h1>
                <p>Hello and welcome to Front. Please, read our Terms and Conditions of Use ("Terms") and Privacy Policy carefully because they affect your legal rights, including an agreement to resolve any disputes that may arise between us by arbitration
                    on an individual basis instead of by class actions or jury trials. We hope you're sitting comfortably and listening to some great music.</p>
                <p>Here we go…</p>
            </div>
        </div>

        <!-- SVG Background Shapes -->
        <div id="SVGbgElements2" class="d-none d-lg-block w-lg-40 content-centered-y right-0 z-index-n1 ml-9" style="">
            <figure class="ie-bg-elements-2">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 849.4 419.7" style="enable-background:new 0 0 849.4 419.7;" xml:space="preserve" class="injected-svg js-svg-injector" data-parent="#SVGbgElements2">
                <g>
                	<linearGradient id="bgElements_1_" gradientUnits="userSpaceOnUse" x1="0.644" y1="109.4822" x2="84.356" y2="109.4822">
                		<stop class="stop-color-warning" offset="7.500810e-08" style="stop-color:#FFC107"></stop>
                		<stop class="stop-color-danger" offset="1" style="stop-color:#DE4437"></stop>
                	</linearGradient>
                	<path fill="url(#bgElements_1_)" d="M77.6,157.5L77.6,157.5c-7.3,5.4-17.7,3.7-23.1-3.6L3.8,84.5c-5.4-7.3-3.7-17.7,3.6-23.1l0,0   c7.3-5.4,17.7-3.7,23.1,3.6l50.7,69.4C86.5,141.8,84.9,152.2,77.6,157.5z"></path>
                </g>
                <g>
                	<linearGradient id="bgElements_2_" gradientUnits="userSpaceOnUse" x1="366.1731" y1="39.5945" x2="430.9116" y2="39.5945">
                		<stop class="stop-color-primary" offset="7.500810e-08" style="stop-color:#377DFF"></stop>
                		<stop class="stop-color-info" offset="1" style="stop-color:#00DFFC"></stop>
                	</linearGradient>
                	<path fill="url(#bgElements_2_)" d="M425.7,76.7L425.7,76.7c-5.7,4.1-13.7,2.9-17.8-2.8l-39.2-53.7c-4.1-5.7-2.9-13.7,2.8-17.8l0,0   c5.7-4.1,13.7-2.9,17.8,2.8l39.2,53.7C432.6,64.6,431.4,72.6,425.7,76.7z"></path>
                </g>
                <linearGradient id="bgElements_3_" gradientUnits="userSpaceOnUse" x1="716" y1="109.4822" x2="739" y2="109.4822">
                	<stop class="stop-color-primary" offset="7.500810e-08" style="stop-color:#377DFF"></stop>
                	<stop class="stop-color-info" offset="1" style="stop-color:#00DFFC"></stop>
                </linearGradient>
                <circle fill="url(#bgElements_3_)" cx="727.5" cy="109.5" r="11.5"></circle>
                <linearGradient id="bgElements_4_" gradientUnits="userSpaceOnUse" x1="0" y1="317.4822" x2="29" y2="317.4822">
                	<stop class="stop-color-warning" offset="7.500810e-08" style="stop-color:#FFC107"></stop>
                	<stop class="stop-color-danger" offset="1" style="stop-color:#DE4437"></stop>
                </linearGradient>
                <circle fill="url(#bgElements_4_)" cx="14.5" cy="317.5" r="14.5"></circle>
                <g>
                	<linearGradient id="bgElements_5_" gradientUnits="userSpaceOnUse" x1="139.1731" y1="371.5945" x2="203.9116" y2="371.5945">
                		<stop class="stop-color-primary" offset="7.500810e-08" style="stop-color:#377DFF"></stop>
                		<stop class="stop-color-info" offset="1" style="stop-color:#00DFFC"></stop>
                	</linearGradient>
                	<path fill="url(#bgElements_5_)" d="M198.7,408.7L198.7,408.7c-5.7,4.1-13.7,2.9-17.8-2.8l-39.2-53.7c-4.1-5.7-2.9-13.7,2.8-17.8l0,0   c5.7-4.1,13.7-2.9,17.8,2.8l39.2,53.7C205.6,396.6,204.4,404.6,198.7,408.7z"></path>
                </g>
                <g>
                	<linearGradient id="bgElements_6_" gradientUnits="userSpaceOnUse" x1="765.644" y1="368.4822" x2="849.356" y2="368.4822">
                		<stop class="stop-color-warning" offset="7.500810e-08" style="stop-color:#FFC107"></stop>
                		<stop class="stop-color-danger" offset="1" style="stop-color:#DE4437"></stop>
                	</linearGradient>
                	<path fill="url(#bgElements_6_)" d="M842.6,416.5L842.6,416.5c-7.3,5.4-17.7,3.7-23.1-3.6l-50.7-69.4c-5.4-7.3-3.7-17.7,3.6-23.1v0   c7.3-5.4,17.7-3.7,23.1,3.6l50.7,69.4C851.5,400.8,849.9,411.2,842.6,416.5z"></path>
                </g>
                </svg>
            </figure>
        </div>
        <!-- End SVG Background Shapes -->
    </div>
    <!-- End Terms Title Section -->

    <!-- Terms Content Section -->
    <div class="bg-light">
        <div class="container space-2 space-md-3">
            <div class="row">
                <div id="stickyBlockStartPoint" class="col-md-4 col-lg-3 mb-7 mb-md-0" style="">
                    <!-- Nav -->
                    <nav class="js-sticky-block card border-0 bg-primary" data-offset-target="#logoAndNav" data-parent="#stickyBlockStartPoint" data-sticky-view="md" data-start-point="#stickyBlockStartPoint" data-end-point="#stickyBlockEndPoint" data-offset-top="24" data-offset-bottom="24"
                        style="">
                        <ul class="js-scroll-nav list-group list-group-transparent list-group-white list-group-flush list-group-borderless py-3 px-5">
                            <li class="active">
                                <a class="list-group-item list-group-item-action py-3" href="#intro">Introduction</a>
                            </li>
                            <li class="">
                                <a class="list-group-item list-group-item-action py-3" href="#services">Using our services</a>
                            </li>
                            <li class="">
                                <a class="list-group-item list-group-item-action py-3" href="#privacy">Privacy and copyright protection</a>
                            </li>
                            <li class="">
                                <a class="list-group-item list-group-item-action py-3" href="#yourContent">Your content in our services</a>
                            </li>
                        </ul>
                    </nav>
                    <!-- End Nav -->
                </div>

                <div class="col-md-8 col-lg-9">
                    <div id="intro" class="space-bottom-2 active">
                        <!-- Title -->
                        <div class="mb-3">
                            <h3 class="text-primary font-weight-semi-bold">Introduction</h3>
                        </div>
                        <!-- End Title -->

                        <!-- Text -->
                        <p>Thanks for using our products and services ("Services"). The Services are provided by Pixeel Ltd. ("Front"), located at 153 Williamson Plaza, Maggieberg, MT 09514, England, United Kingdom.
                        </p>
                        <p>By using our Services, you are agreeing to these terms. Please read them carefully.</p>
                        <p>Our Services are very diverse, so sometimes additional terms or product requirements (including age requirements) may apply. Additional terms will be available with the relevant Services, and those additional terms become part
                            of your agreement with us if you use those Services.</p>
                        <!-- End Text -->
                    </div>

                    <hr class="my-0">

                    <div id="services" class="space-2 active">
                        <!-- Title -->
                        <div class="mb-3">
                            <h3 class="text-primary font-weight-semi-bold">Using our services</h3>
                        </div>
                        <!-- End Title -->

                        <!-- Text -->
                        <p>You must follow any policies made available to you within the Services.</p>
                        <p>Don't misuse our Services. For example, don't interfere with our Services or try to access them using a method other than the interface and the instructions that we provide. You may use our Services only as permitted by law, including
                            applicable export and re-export control laws and regulations. We may suspend or stop providing our Services to you if you do not comply with our terms or policies or if we are investigating suspected misconduct.</p>
                        <p>Using our Services does not give you ownership of any intellectual property rights in our Services or the content you access. You may not use content from our Services unless you obtain permission from its owner or are otherwise
                            permitted by law. These terms do not grant you the right to use any branding or logos used in our Services. Don't remove, obscure, or alter any legal notices displayed in or along with our Services.</p>
                        <!-- End Text -->
                    </div>

                    <hr class="my-0">

                    <div id="privacy" class="space-2 active">
                        <!-- Title -->
                        <div class="mb-3">
                            <h3 class="text-primary font-weight-semi-bold">Privacy and copyright protection</h3>
                        </div>
                        <!-- End Title -->

                        <!-- Text -->
                        <p>Front's privacy policies explain how we treat your personal data and protect your privacy when you use our Services. By using our Services, you agree that Front can use such data in accordance with our privacy policies.</p>
                        <p>We respond to notices of alleged copyright infringement and terminate accounts of repeat infringers according to the process set out in the U.S. Digital Millennium Copyright Act.</p>
                        <p>We provide information to help copyright holders manage their intellectual property online. If you think somebody is violating your copyrights and want to notify us, you can find information about submitting notices and Front's
                            policy about responding to notices in <a href="help.html">our Help Center</a>.</p>
                        <!-- End Text -->
                    </div>

                    <hr class="my-0">

                    <div id="yourContent" class="space-top-2 active">
                        <!-- Title -->
                        <div class="mb-3">
                            <h3 class="text-primary font-weight-semi-bold">Your content in our services</h3>
                        </div>
                        <!-- End Title -->

                        <!-- Text -->
                        <p>Some of our Services allow you to upload, submit, store, send or receive content. You retain ownership of any intellectual property rights that you hold in that content. In short, what belongs to you stays yours.</p>
                        <p>When you upload, submit, store, send or receive content to or through our Services, you give Front (and those we work with) a worldwide license to use, host, store, reproduce, modify, create derivative works (such as those resulting
                            from translations, adaptations or other changes we make so that your content works better with our Services), communicate, publish, publicly perform, publicly display and distribute such content. The rights you grant in this
                            license are for the limited purpose of operating, promoting, and improving our Services, and to develop new ones. This license continues even if you stop using our Services (for example, for a business listing you have added
                            to Front Maps). Some Services may offer you ways to access and remove content that has been provided to that Service. Also, in some of our Services, there are terms or settings that narrow the scope of our use of the content
                            submitted in those Services. Make sure you have the necessary rights to grant us this license for any content that you submit to our Services.</p>
                        <!-- End Text -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Terms Content Section -->

    <div id="stickyBlockEndPoint"></div>
</main>
 