<!-- ========== MAIN CONTENT ========== -->
<main class="content" id="content" role="main">
    <div class="container space-2 space-md-2">
        <div class="row">
            <div class="col-sm-10 col-md-10 col-lg-10 ml-md-auto mr-md-auto">
               
               <?php
                include("topedit.phtml"); 
                ?> 
                <div class="row">
                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <?php   
                        include("menu.phtml"); 
                        ?>
                    </div>
                    <div class="col-sm-9 col-md-9 col-lg-9">
                        <!-- Card -->
                        <div class="card mb-3">
                            <div class="card-body"> 
                                
                                <div id="transfer-list">
                                    <?php  
                                    //$amount_net = $detail['amount_net']; 
                                    //$fee = ($detail['service_charge']+$transfer_fee); 
                                    $amount_net = ($detail['total']-$detail['service_charge']);  
                                    ?> 
                                    <p><?=$this->translate('Your current balance is :');?> <?=number_format($detail['total'], 2);?> <?=$this->translate('THB');?></p>
                                    <?php 
                                    if($detail['total']>=1000){   
                                        if(0){  
                                    ?>
                                        <p><?=$this->translate('Service charge :');?> <?=number_format($detail['service_charge'], 2);?> <?=$this->translate('THB');?></p>
                                        <p><?=$this->translate('Omise transfer fee :');?> <?=number_format($transfer_fee, 2);?> <?=$this->translate('THB');?></p>
                                        <p><?=$this->translate('Your withdrawable amount is :');?> <?=number_format($amount_net+$transfer_fee, 2);?> <?=$this->translate('THB');?></p> 
                                        <?php
                                        }
                                        ?>
                                    <button type="button" class="btn btn-primary btn-new-bank"><?=$this->translate('Initiate a bank transfer');?></button>
                                    <?php
                                    }    
                                    ?>
                                    <p class="mt-5"><?=$this->translate('Balance transfer history');?></p>
                                    
                                    <table class="table table-light">
                                      <thead>
                                        <tr>
                                          <th scope="col"><?=$this->translate('Amount');?></th>
                                          <!--
                                          <th scope="col"><?=$this->translate('Fee');?></th>
                                          -->
                                          <th scope="col"><?=$this->translate('Bank Account');?></th>
                                          <th scope="col"><?=$this->translate('Status');?></th>
                                          <th scope="col"><?=$this->translate('Date');?></th>
                                        </tr>
                                      </thead>
                                      <tbody class="font-size-1">
                                        <?php
                                        //print_r($transfer_list);
                                        if(!empty($transfer_list['total'])){
                                            foreach($transfer_list['data'] as $key=>$value){  
                                        ?> 
                                                <tr>
                                                  <td class="align-middle font-weight-normal"><?=number_format(($value['transfer_amount']),2);?> <?=$this->translate('THB');?></td>
                                                  <!--
                                                  <td class="align-middle"><?=number_format($value['transfer_fee'],2);?> THB</td>
                                                  -->
                                                  <td class="align-middle"><?=$value['bank_acc_number'];?>-<?=$value['bank_name'];?></td>
                                                  <td class="align-middle"> 
                                                    <?php
                                                    if($value['status']==3){
                                                    ?>  
                                                        <span class="fas fa-circle text-success small mr-1"></span> <?=$this->translate('Paid');?>
                                                    <?php
                                                    }else if($value['status']==2){ 
                                                    ?>
                                                        <span class="fas fa-circle text-warning small mr-1"></span> <?=$this->translate('Sent');?>
                                                    <?php
                                                    }else if($value['status']==1){ 
                                                    ?>
                                                        <span class="fas fa-circle text-primary small mr-1"></span> <?=$this->translate('In progress');?>
                                                    <?php
                                                    }else{ 
                                                    ?>
                                                        <span class="fas fa-circle text-danger small mr-1"></span> <?=$this->translate('Fail');?>
                                                    <?php
                                                    }
                                                    ?>
                                                  </td>
                                                  <td class="align-middle"><?=date("d M Y H:i", strtotime($value['createdate']))?></td>
                                                </tr> 
                                            
                                        <?php
                                            }
                                        }else{
                                        ?>
                                        <tr>
            					    		<td colspan="4" align="center"><?=$this->translate('No Data');?></td>
            					    	</tr>
                                        <?php
                                        }
                                        ?>
                                        <?php
                                        if(0){  
                                        ?>
                                        <tr>
                                          <td class="align-middle font-weight-normal">80,000 THB</td>
                                          <td class="align-middle">02000XXXXX-Kasikorn</td>
                                          <td class="align-middle">
                                            <span class="fas fa-circle text-primary small mr-1"></span>
                                            In progress
                                          </td>
                                          <td class="align-middle">21 March 2019</td>
                                        </tr> 
                                        <?php
                                        }
                                        ?>
                                      </tbody>
                                    </table>
                                </div>
                                <?php
                                if($detail['total']>=1000){  
                                ?>
                                <div id="transfer-add">  
                                    <p><?=$this->translate('Please add a bank account we should send the');?> <?=number_format($amount_net+$transfer_fee, 2);?> <?=$this->translate('THB to');?></p>
                                    <form class="js-validate mx-md-auto mt-5" name="bank-form" id="bank-form" action="" onsubmit="return false;" method="post" enctype="multipart/form-data" novalidate="novalidate">
                                        <div class="row">
                                            <div class="col-sm-12 col-md-8 col-lg-8 text-left">
                                                <div class="js-form-message form-group"> 
                                                    <label for="fullname"><?=$this->translate('Receipient First & Last Name'); ?></label>
                                                    <input type="text" class="form-control" name="name" id="fullname" placeholder="<?=$this->translate('Receipient First & Last Name'); ?>" data-msg="<?=$this->translate('Please enter receipient first & last name.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
                                                </div>
                                                <div class="js-form-message form-group"> 
                                                    <label for="bank_country"><?=$this->translate('Bank account country'); ?></label>
                                                    <select class="form-control" id="bank_country" name="country" data-msg="<?=$this->translate('Please enter bank account country.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
                                                       <option value="th"><?=$this->translate('Thailand'); ?></option>
                                                       <option value="sg"><?=$this->translate('Singapore'); ?></option>
                                                    </select>
                                                </div>
                                                
                                                <div class="js-form-message form-group"> 
                                                    <label for="bank_name"><?=$this->translate('Bank account name'); ?></label>
                                                    <input type="text" class="form-control" name="acc_name" id="bank_name" placeholder="<?=$this->translate('Bank account name'); ?>" data-msg="<?=$this->translate('Please enter bank account name.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
                                                </div>
                                                
                                                <div class="js-form-message form-group"> 
                                                    <label for="bank_number"><?=$this->translate('Bank account number'); ?></label>
                                                    <input type="number" class="form-control" name="acc_number" id="bank_number" placeholder="<?=$this->translate('Bank account number'); ?>" data-msg="<?=$this->translate('Please enter bank account number.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
                                                </div> 
                                                
                                                <div class="js-form-message form-group">  
                                                    <label for="bank_number"><?=$this->translate('Bank name'); ?></label>
                                                    <select class="form-control" id="bank_account" name="bank_name" data-msg="<?=$this->translate('Plase select bank name.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
                                                       <?php
                                                       if($this->lang=='th'){
                                                           $b_lang = 'th';
                                                       }else{
                                                           $b_lang = 'sg';
                                                       }
                                                       $b_lang = 'th'; 
                                                       foreach($banks[$b_lang] as $key=>$val){ 
                                                       ?>
                                                       <option value="<?=$key;?>"><?=$val;?></option>
                                                       <?php
                                                       } 
                                                       ?>
                                                    </select>    
                                                </div>
                                            </div> 
                                            <div class="col-sm-12 col-md-4 col-lg-4 text-left">
                                                
                                                <div class="js-form-message form-group"> 
                                                    <label for="bank_account"><?=$this->translate('Type of bank account'); ?></label>
                                                    <select class="form-control" id="bank_type" name="type" data-msg="<?=$this->translate('Plase select type of bank account.'); ?>" data-error-class="u-has-error" data-success-class="u-has-success">
                                                       <option value="individual"><?=$this->translate('Individual'); ?></option>
                                                       <option value="corporation"><?=$this->translate('Corperation'); ?></option>
                                                    </select>
                                                </div>
                                                
                                            </div> 
                                            <div class="col-sm-12 col-md-12 col-lg-12 text-left mt-3 mb-5">
                                                <button type="submit" class="btn btn-primary transition-3d-hover btn-transferfund"><?=$this->translate('Create bank account'); ?></button>
                                                <button type="button" class="btn btn-gray btn-back transition-3d-hover"><?=$this->translate('Back'); ?></button>
                                            </div> 
                                        </div>
                                    </form>
                                </div>
                                <?php
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- ========== END MAIN CONTENT ========== -->
<?php
if($detail['total']>=1000){  
?>
<script type="text/javascript">
var bank_json = JSON.parse('<?=json_encode($banks);?>'); 
var id = '<?=$id;?>';
$(".btn-new-bank").click(function(){
    $("#transfer-list").hide(); 
    $("#transfer-add").show();
});
$("#bank_country").change(function(){
    var bank = bank_json[$(this).val()];
    var option = '';
    $.each(bank, function(i, item) {
        option += '<option value="'+i+'">'+item+'</option>';
    }); 
    $("#bank_account").html(option);
});

$("form[name='bank-form']").validate({ 
  rules: {  
    name: "required",
    acc_name: "required",
    acc_number: "required"
  },     
  messages: {
    name: $('#fullname').data('msg'),
    acc_name: $('#bank_name').data('msg'),
    acc_number:$('#bank_number').data('msg')
  },    
  submitHandler: function(form) {
    btn_loader = $('.btn-transferfund');  
    $('.btn-transferfund').buttonLoader('start'); 
    
    $.ajax({   
        url: base_url+action+'/'+id+'/?act=transferfund&rd='+makeid(), 
        type: "POST",   
        dataType: "json",  
        data: $(form).serialize(),    
        cache: false,              
        processData: false,      
        success: function(data) { 
            
            setTimeout(function(){    
				$(btn_loader).buttonLoader('stop');	
		 	},500);
		 	
			if(data.status==200){ 
			 	$("#transfer-list").show(); 
                $("#transfer-add").hide(); 
                window.location = base_url+action+'/'+id+'/?rd='+makeid();
			}else{ 
			    alert_error(data.items); 
				setTimeout(function(){   
    				$(btn_loader).buttonLoader('stop');	
    		 	},100);   
			} 
        },  
        error: function(e) {
            console.log(e);
            setTimeout(function(){   
				$(btn_loader).buttonLoader('stop');	
		 	},100);    
		    alert_error(error_alert);  
        } 
    });
    
    
    return false;  
  }, 
  highlight: function(element, errorClass, validClass) {
    $(element).removeClass('success-class').addClass('error-class');
  },
  unhighlight: function(element, errorClass, validClass) {
    $(element).removeClass('error-class').addClass('success-class');
  }
});

$(".btn-back").click(function(){
    $("#transfer-add").hide(); 
    $("#transfer-list").show();
});
</script>
<?php
}
?>