<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header"> 
      	<h1>
        	<?=$this->page_name;?> 
        	<small>Add <?=$this->page_name;?></small> 
      	</h1> 
      	<ol class="breadcrumb">
        	<li><a href="<?php echo $this->url('home');?>dashboard/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        	<li><a href="<?php echo $this->url('home');?>admin/<?=$this->action;?>/"><?=$this->page_name;?></a></li>
        	<li class="active">new</li>
      	</ol>
    </section>

    <!-- Main content --> 
    <section class="content">
      	<div class="row">
        	<!-- right column -->
        	<div class="col-md-6"> 
          		<!-- general form elements -->
          		<div class="box box-primary">
            		<div class="box-header with-border"> 
              		<h3 class="box-title">Information</h3>
            	</div><!-- /.box-header -->
            	<!-- form start -->
            	<form role="form" action="<?php echo $this->url('home');?>admin/<?=$this->action;?>/?task=add" enctype="multipart/form-data" name="quest" method="post">
                	<div class="box-body">
                    	<div class="form-group">
                  			<label for="name">Name</label> 
                  			<input type="text" class="form-control " id="name" name="data[name]" placeholder="name" required /> 
                		</div>
                		<div class="form-group">
                  			<label for="detail">Detail</label> 
                  			<textarea class="form-control " id="detail" name="data[detail]" placeholder="Detail" rows="3"></textarea> 
                		</div> 
                        <div class="form-group"> 
                  			<label for="exampleInputFile">Banner 695x460</label>  
                  			<input type="file" id="pic" name="pic" onchange="imagePreview(this,'img-preview')" required>
                  			<div id="img-preview"></div>  
                		</div>  
                        <div class="checkbox">
                  			<label>
                    			<input type="checkbox" name="status" value="1" data-toggle="toggle" data-off="Disabled" data-on="Enabled"> Status
                  			</label>
                		</div>
              		</div><!-- /.box-body -->

              		<div class="box-footer">
                		<button type="submit" class="btn btn-primary" style="float:right;">Submit</button>
              		</div>
            	</form>
          	</div>
		</div>
  	</section>
</div>