 
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      	<h1>
        	<?=$detail['name'];?>
        	<small>Preview</small>
      	</h1>
      	<ol class="breadcrumb">
        	<li><a href="<?php echo $this->url('home');?>admin/dashboard/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        	<li><a href="<?php echo $this->url('home');?>admin/<?=$this->action;?>/"><?=$this->page_name;?></a></li>
        	<li class="active">edit</li>
      	</ol>
    </section>

    <!-- Main content -->
    <section class="content">
      	<div class="row">
      	   
        	<!-- left column -->
        	<div class="col-md-3">
            	<div class="box box-primary"></div>
                <center><img src="<?=$detail['image'];?>" class="img-responsive" alt="<?=$detail['name'];?>"></center>
            </div>
        	<!-- right column -->
        	<div class="col-md-6"> 
          		<!-- general form elements -->
          		<div class="box box-primary">
            		<div class="box-header with-border"> 
              		<h3 class="box-title">Information</h3>
            	</div><!-- /.box-header --> 
            	<!-- form start -->
            	<form role="form" action="<?php echo $this->url('home');?>admin/<?=$this->action;?>/?task=edit&id=<?=$detail['id'];?>" name="quest" enctype="multipart/form-data" method="post">
                	<input type="hidden" name="id" id="id" value="<?=$detail['id'];?>">
              		<div class="box-body"> 
                    	<div class="form-group">
                  			<label for="name">Name</label> 
                  			<input type="text" class="form-control " id="name" name="data[name]" placeholder="name" value="<?=$detail['name'];?>" required /> 
                		</div>
                		<div class="form-group">
                  			<label for="detail">Detail</label> 
                  			<textarea class="form-control " id="detail" name="data[detail]" placeholder="Detail" rows="3"><?=$detail['detail'];?></textarea> 
                		</div>
                        <div class="form-group">  
                  			<label for="exampleInputFile">Banner 695x460</label>
                  			<input type="file" id="pic" name="pic" onchange="imagePreview(this,'img-preview')">
                  			<div id="img-preview"></div>  
                		</div> 
                        <div class="checkbox">
                  			<label>
                    			<input type="checkbox" name="status" value="1" data-toggle="toggle" data-off="Disabled" data-on="Enabled"  <?=($detail['status']==1)?'checked':'';?>> Active
                  			</label>
                		</div>
              		</div>
              		<div class="box-footer">
                		<button type="submit" class="btn btn-primary" style="float:right; padding-right:10px;">Submit</button>
              		</div>
            	</form>
          	</div>
		</div>
  	</section>
</div>