<?php 
echo $this->doctype();
 
if($this->controller == 'Application\Controller\Admin'){ 
?>
<html lang="en"> 
    <head>
        <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=UTF-8">
        <meta http-equiv="Cache-control" content="public">
        <META HTTP-EQUIV="EXPIRES" CONTENT="<?php echo gmdate("D, d M Y H:i:s", time() + (60*60)) . " GMT"; ?>">
        <meta http-equiv="cleartype" content="on">
        <meta name="MobileOptimized" content="767">
        <meta name="HandheldFriendly" content="True">
        <meta name='mobile-web-app-capable' content='yes'>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable = no">
        <meta name="theme-color" content="#ffffff">
        <meta name='application-name' content='ZF3'> 
	    <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name='apple-mobile-web-app-status-bar-style' content='black'>
        <meta name='apple-mobile-web-app-title' content='ZF3'>
	    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
        <META NAME="AUTHOR" CONTENT="Tonytoons">
        <META name="revisit-after" content="7 days">
        <META NAME="COPYRIGHT" CONTENT="&copy; <?php echo date('Y') ?> ZF3">
        <title><?=!empty($page_name)?$page_name:$this->translate('title'); ?></title>
        
        <!-- Bootstrap 3.3.7 -->
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/bower_components/bootstrap/dist/css/bootstrap.min.css">
          <!-- Font Awesome -->
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/bower_components/font-awesome/css/font-awesome.min.css">
          <!-- Ionicons -->
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/bower_components/Ionicons/css/ionicons.min.css">
          <!-- Theme style -->
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/dist/css/AdminLTE.min.css">
          <!-- AdminLTE Skins. Choose a skin from the css/skins
               folder instead of downloading all of them to reduce the load. -->
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/dist/css/skins/_all-skins.min.css">
          <!-- Morris chart -->
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/bower_components/morris.js/morris.css">
          <!-- jvectormap -->
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/bower_components/jvectormap/jquery-jvectormap.css">
          <!-- Date Picker -->
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
          <!-- Daterange picker -->
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/bower_components/bootstrap-daterangepicker/daterangepicker.css">
          <!-- bootstrap wysihtml5 - text editor -->
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
           
          <link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/dist/css/css.css">  
          
        	<!-- jQuery 3 -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/plugins/jQuery/jQuery-2.1.4.min.js"></script>
        	 
        	<!-- jQuery UI 1.11.4 -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/jquery-ui/jquery-ui.min.js"></script>
        	<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        	
        	<script>
        	  $.widget.bridge('uibutton', $.ui.button);
        	</script>
        	<!-- Bootstrap 3.3.7 -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        	<!-- Morris.js charts -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/raphael/raphael.min.js"></script>
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/morris.js/morris.min.js"></script>
        	<!-- Sparkline -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
        	<!-- jvectormap -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
        	<script src="<?php echo $this->url('home'); ?>backoffice/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        	<!-- jQuery Knob Chart -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
        	<!-- daterangepicker -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/moment/min/moment.min.js"></script>
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
        	<!-- datepicker -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        	<!-- Bootstrap WYSIHTML5 -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
        	<!-- Slimscroll -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
        	<!-- FastClick -->
        	<script src="<?php echo $this->url('home'); ?>backoffice/bower_components/fastclick/lib/fastclick.js"></script>
        	
        	<link rel="stylesheet" href="<?php echo $this->url('home'); ?>backoffice/plugins/bootstrap-toggle/css/bootstrap-toggle.min.css">
        	
        	<script src="<?php echo $this->url('home'); ?>backoffice/plugins/bootstrap-toggle/js/bootstrap-toggle.min.js"></script> 
        	 
        	<script src="<?php echo $this->url('home'); ?>backoffice/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js"></script>
        	
        	<!-----------------   DataTable   ------------------->  
                
            <link href="<?php echo $this->url('home'); ?>backoffice/plugins/datatables/media/css/rowReorder.dataTables.min.css" rel="stylesheet">
            <link href="<?php echo $this->url('home'); ?>backoffice/plugins/datatables/media/css/dataTables.bootstrap.css" rel="stylesheet">
            
            <script src="<?php echo $this->url('home'); ?>backoffice/plugins/datatables/media/js/jquery.dataTables.js"></script>
            <script src="<?php echo $this->url('home'); ?>backoffice/plugins/datatables/media/js/dataTables.rowReorder.min.js"></script>     
            <script src="<?php echo $this->url('home'); ?>backoffice/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
               
            <?php
            if(0){
            ?>
            <!-- include summernote css/js-->
        	<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css" rel="stylesheet">
        	<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js"></script>
        	<?php
            }
        	?>
        	<link href="<?php echo $this->url('home'); ?>backoffice/plugins/summernote/summernote.css" rel="stylesheet">
        	<script src="<?php echo $this->url('home'); ?>backoffice/plugins/summernote/summernote.js"></script>  
        	<script type="text/javascript">  
                var basePath = '<?php echo $this->baseUrl; ?>'; 
                var action = '<?php echo $this->action;?>';
            </script>
          
             <!-- Favicon and touch icons -->
            <link rel="shortcut icon" href="<?php echo $this->url('home'); ?>images/favicon/favicon.png" type="image/x-icon">   
            <link rel="apple-touch-icon" type="image/x-icon" href="<?php echo $this->url('home'); ?>images/favicon/apple-touch-icon-57-precomposed.png">
            <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="<?php echo $this->url('home'); ?>images/favicon/apple-touch-icon-72-precomposed.png">
            <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="<?php echo $this->url('home'); ?>images/favicon/apple-touch-icon-114-precomposed.png">
            <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="<?php echo $this->url('home'); ?>images/favicon/apple-touch-icon-144-precomposed.png">

        
          <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
          <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
          <!--[if lt IE 9]>
          	
          <!--
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script> 
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
          -->
          <![endif]-->
        
          <!-- Google Font -->
          <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
            
        
    </head>
    <body class="hold-transition <?php if($this->action=='login'){ ?>login-page<?php }else{ ?>skin-blue sidebar-mini<?php } ?>">  
        <div class="wrapper"> 
        <?php echo $this->content; ?> 
        </div>  
        <!-- ./wrapper -->  
    </body>  
    <!-- autosize js --> 
    <script src="<?php echo $this->url('home'); ?>backoffice/js/autosize.min.js"></script> 
      
    <!-- AdminLTE App -->
    <script src="<?php echo $this->url('home'); ?>backoffice/dist/js/adminlte.min.js"></script>
    <script src="<?php echo $this->url('home'); ?>backoffice/js/datatables.js"></script>
    <script src="<?php echo $this->url('home'); ?>backoffice/js/admin.js"></script> 
     <script src="<?php echo $this->url('home'); ?>backoffice/dist/js/js.js"></script>
     <?php 
    if(0){ 
    ?>
    <script src="<?php echo $this->url('home'); ?>backoffice/js/js.js"></script>
    <?php
    }   
    ?>
</html>
<?php
}else if($this->controller == 'Application\Controller\Index'){  
   
?>
<html lang="en"> 
    <head>
        <?php 
        if ($this->headTitle() == 'SET') {  
            echo $this->headTitle();    
        } else {  
            echo $this->headTitle('');      
        }
        echo $this->headMeta();      
        ?> 
        <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=UTF-8">
        <meta http-equiv="Cache-control" content="public">
        <META HTTP-EQUIV="EXPIRES" CONTENT="<?php echo gmdate("D, d M Y H:i:s", time() + (60*60)) . " GMT"; ?>">
        <meta http-equiv="cleartype" content="on">
        <meta name="MobileOptimized" content="767">
        <meta name="HandheldFriendly" content="True">
        <meta name='mobile-web-app-capable' content='yes'>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable = no">
        <meta name="theme-color" content="#ffffff">
        <meta name='application-name' content='ZF3'> 
	    <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name='apple-mobile-web-app-status-bar-style' content='black'>
        <meta name='apple-mobile-web-app-title' content='ZF3'>
	    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
        <META NAME="AUTHOR" CONTENT="Tonytoons">
        <META name="revisit-after" content="7 days"> 
        <META NAME="COPYRIGHT" CONTENT="&copy; <?php echo date('Y') ?> ZF3">
        
        
         <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="<?php echo $this->url('home'); ?>images/favicon/favicon.png" type="image/x-icon">   
        <link rel="apple-touch-icon" type="image/x-icon" href="<?php echo $this->url('home'); ?>images/favicon/apple-touch-icon-57-precomposed.png">
        <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="<?php echo $this->url('home'); ?>images/favicon/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="<?php echo $this->url('home'); ?>images/favicon/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="<?php echo $this->url('home'); ?>images/favicon/apple-touch-icon-144-precomposed.png">

        <!-- jquery ui css -->
        <link href="<?php echo $this->url('home'); ?>css/jquery-ui.min.css" rel="stylesheet" type="text/css"/>
        <!-- Bootstrap -->
        <link href="<?php echo $this->url('home'); ?>css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!--Animate css-->
        <link href="<?php echo $this->url('home'); ?>css/animate.min.css" rel="stylesheet" type="text/css"/>
        <!-- Navigation css-->
        <link href="<?php echo $this->url('home'); ?>bootsnav/css/bootsnav.css" rel="stylesheet" type="text/css"/>
        <!-- youtube css -->
        <link href="<?php echo $this->url('home'); ?>css/RYPP.css" rel="stylesheet" type="text/css"/>
        <!-- font awesome -->
        <link href="<?php echo $this->url('home'); ?>font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <!-- themify-icons -->
        <link href="<?php echo $this->url('home'); ?>themify-icons/themify-icons.css" rel="stylesheet" type="text/css"/>
        <!-- weather-icons -->
        <link href="<?php echo $this->url('home'); ?>weather-icons/css/weather-icons.min.css" rel="stylesheet" type="text/css"/>
        <!-- flat icon -->
        <link href="<?php echo $this->url('home'); ?>css/flaticon.css" rel="stylesheet" type="text/css"/>
        <!-- Important Owl stylesheet -->
        <link href="<?php echo $this->url('home'); ?>owl-carousel/owl.carousel.css" rel="stylesheet" type="text/css"/>
        <!-- Default Theme -->
        <link href="<?php echo $this->url('home'); ?>owl-carousel/owl.theme.css" rel="stylesheet" type="text/css"/>
        <!-- owl transitions -->
        <link href="<?php echo $this->url('home'); ?>owl-carousel/owl.transitions.css" rel="stylesheet" type="text/css"/>
        <!-- style css -->
        <!--<link href="<?php echo $this->url('home'); ?>css/style.css" rel="stylesheet" type="text/css"/>-->
        <link href="<?php echo $this->url('home'); ?>css/main.css" rel="stylesheet" type="text/css"/>
        <!-- offcanvas -->
        <link href="<?php echo $this->url('home'); ?>css/offcanvas.css" rel="stylesheet" type="text/css"/>
        <script type="text/javascript">  
            var basePath = '<?php echo $this->baseUrl; ?>'; 
            var action = '<?php echo $action;?>';
        </script> 
    </head>
    <body>
        <!-- PAGE LOADER -->
        <div class="se-pre-con"></div>
        <?php echo $this->content; ?>
        <!-- *** END OF /. SUB FOOTER *** -->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="<?php echo $this->url('home'); ?>js/jquery.min.js"></script>
        <!-- jquery ui js -->
        <script src="<?php echo $this->url('home'); ?>js/jquery-ui.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="<?php echo $this->url('home'); ?>js/bootstrap.min.js"></script>
        <!-- Bootsnav js -->
        <script src="<?php echo $this->url('home'); ?>bootsnav/js/bootsnav.js"></script>
        <!-- theia sticky sidebar -->
        <script src="<?php echo $this->url('home'); ?>js/theia-sticky-sidebar.js"></script>
        <!-- youtube js -->
        <!--<script src="<?php echo $this->url('home'); ?>js/RYPP.js"></script>-->
        <!-- owl include js plugin -->
        <script src="<?php echo $this->url('home'); ?>owl-carousel/owl.carousel.min.js"></script>
        <!-- Holder js -->
        <script src="<?php echo $this->url('home'); ?>js/holder.min.js"></script>
        <!-- custom js -->
        <script src="<?php echo $this->url('home'); ?>js/custom.js"></script>
        <!-- offcanvas js -->
        <script src="<?php echo $this->url('home'); ?>js/offcanvas.js"></script>
    </body>
</html> 

<?php  
}else {
?>
<html lang="en"> 
    <head>
        <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=UTF-8">
        <meta http-equiv="Cache-control" content="public">
        <META HTTP-EQUIV="EXPIRES" CONTENT="<?php echo gmdate("D, d M Y H:i:s", time() + (60*60)) . " GMT"; ?>">
        <meta http-equiv="cleartype" content="on">
        <meta name="MobileOptimized" content="767">
        <meta name="HandheldFriendly" content="True">
        <meta name='mobile-web-app-capable' content='yes'>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable = no">
        <link rel="shortcut icon" href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico" type="image/x-icon">
        <link rel="icon" href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico" type="image/x-icon">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->url('home'); ?>img/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->url('home'); ?>img/favicon/favicon-96x96.png">
        <link rel="apple-touch-icon" sizes="57x57" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico">
        <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico">
        <link rel="manifest" href="<?php echo $this->url('home'); ?>manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="<?php echo $this->url('home'); ?>img/icon/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
        <meta name='application-name' content='ZF3'>
	    <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name='apple-mobile-web-app-status-bar-style' content='black'>
        <meta name='apple-mobile-web-app-title' content='ZF3'>
	    <link rel="apple-touch-startup-image" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-180x180.png">
	    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
        <META NAME="AUTHOR" CONTENT="Tonytoons">
        <META name="revisit-after" content="7 days">
        <META NAME="COPYRIGHT" CONTENT="&copy; <?php echo date('Y') ?> ZF3">
        <title><?php echo $this->translate('title'); ?></title>
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
        <!-- Optional theme -->
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">-->
        <?php include_once 'css.phtml'; ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script> 
        <![endif]--> 
    </head> 
    <body>
        <?php echo $this->content; ?>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" defer></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous" defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.4.2/vue.min.js" defer></script>
        <script src="<?php echo $this->url('home'); ?>js/myJS.js" onLoad="init();" defer></script>
    </body>
</html>
<?php
}
echo $this->inlineScript(); 
?>