
  	<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
	<section class="content-header">
 		<h1>
        	<?=$this->page_name;?>
        	<a href="<?php echo $this->url('home');?>admin/<?=$this->action;?>/?task=add"><small> >> New <?=$this->page_name;?></small></a>
      	</h1>
      	<ol class="breadcrumb"> 
        	<li><a href="<?php echo $this->url('home');?>admin/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        	<li class="active">Admin users</li> 
      	</ol>
    </section>
    <!-- Main content -->
    <section class="content">
      	<div class="row">
        	<div class="col-xs-12">
          		<div class="box"> 
            		<div class="box-header"> 
              			<a href="<?php echo $this->url('home');?>admin/<?=$this->action;?>/?task=add" class="btn btn-success"><i class="fa fa-plus"></i> New <?=$this->page_name;?></small></a>
            		</div>
            		<div class="box-body table-responsive"> 
            		    <table id="dataTable" class="display table table-hover table-responsive" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>No.</th> 
                                    <th>Cover</th> 
                              		<th>Name</th>
                              		<th>Category</th>
                              		<th>Views</th>
                              		<th>Create date</th>
                              		<th>Last updated</th>
                              		<th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody id="dataTableBody"> 
								
				            </tbody>
                            <tfoot>
                                <tr>
                                    <th>No.</th> 
                                    <th>Cover</th> 
                              		<th>Name</th>  
                              		<th>Category</th>
                              		<th>Views</th> 
                              		<th>Create date</th>
                              		<th>Last updated</th>
                              		<th>Status</th>
                                    <th>Action</th>
                                </tr> 
                            </tfoot>
                        </table>
            		</div>
          		</div>
        	</div>
      	</div>
    </section><!-- /.content -->
</div>
