<header class="main-header">
    <!-- Logo -->
    <a href="<?php echo $this->url('home');?>admin/" class="logo"> 
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b><?=$title;?></b></span>  
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b><?=$title;?></b></span> 
    </a> 
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a> 

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">        
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="<?php echo $this->url('home');?>admin/admin/act/editForm/id/<?=$admin->id;?>" class="dropdown-toggle" data-toggle="dropdown">
              <?php
              if(!empty($admin->image)){  
              ?>
              <img src="<?php echo $this->urlFile;?>/admin/<?=$admin->image;?>" class="user-image" alt="User Image">
              <?php
              }else{ 
              ?> 
              <img src="<?php echo $this->url('home');?>img/photo_not_available.jpg" class="user-image" alt="User Image">
              <?php
              } 
              ?>
              <span class="hidden-xs"><?=$admin->name;?></span> 
            </a>
            <ul class="dropdown-menu">  
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="<?php echo $this->url('home');?>admin/admin/act/editForm/id/<?=$admin->id;?>" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="<?php echo $this->url('home');?>admin/logout" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li> 
        </ul>
      </div>
    </nav>
</header>